USE vibe16;

SET NAMES utf8;

DROP TABLE IF EXISTS Comment;
CREATE TABLE Comment
(
    `id` INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    `email` VARCHAR(120),
    `text` VARCHAR(120),
    `userId` INT NOT NULL,
    `postedBy` VARCHAR(120),
    `published` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `created` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updated` DATETIME ON UPDATE CURRENT_TIMESTAMP, --  ON UPDATE CURRENT_TIMESTAMP,
    `deleted` BOOLEAN DEFAULT 0,

    FOREIGN KEY (userId) REFERENCES User(id)

) ENGINE INNODB CHARACTER SET utf8;
